#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

filesToCommit=`git diff --name-only --staged`
# echo $filesToCommit

declare -A appsCommands=( ["expense-tracker-api"]="test-et-api" ["expense-tracker-ui"]="test-et-ui"  ["todos-ui"]="test-todo-ui"  ["todos-api"]="test-todo-api")
apps=("expense-tracker-api" "expense-tracker-ui","todos-api"."todos-ui")

commandsToExecute=()
# for loop 
for fileToCommit in $filesToCommit
do
#    echo $fileToCommit
    dirnames=`dirname "$fileToCommit"`
    filename=`basename "$fileToCommit"`

    directorySeparator=/
    s=$fileToCommit$directorySeparator
    folderInFileToCommit=();
    while [[ $s ]]; do
    folderInFileToCommit+=( "${s%%"$directorySeparator"*}" );
    s=${s#*"$directorySeparator"};
    done;

    appThatHasCodeChanges=${folderInFileToCommit[1]}
    # echo $appThatHasCodeChanges


   if [[ "\t${apps[@]}\t"=~"\t${appThatHasCodeChanges}\t"  ]]; then
        commandsToExecute+=( ${appsCommands[$appThatHasCodeChanges]} )
    # else
    #     echo "false"
    fi
done

# detect test command 

# execute test command 
echo $commandsToExecute
npm test