#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

filesToCommit=`git diff --name-only --staged`
# echo $filesToCommit

declare -A appsCommands=( ["expense-tracker-api"]="test-et-api" ["expense-tracker-ui"]="test-et-ui"  ["todos-ui"]="test-todo-ui"  ["todos-api"]="test-todo-api" )
apps=("expense-tracker-api" "expense-tracker-ui","todos-api"."todos-ui")
commandsToExecute=()


for fileToCommit in $filesToCommit
do
    dirnames=`dirname "$fileToCommit"`
    filename=`basename "$fileToCommit"`

    directorySeparator=/
    s=$fileToCommit$directorySeparator
    folderInFileToCommit=();
    while [[ $s ]]; do
    folderInFileToCommit+=( "${s%%"$directorySeparator"*}" );
    s=${s#*"$directorySeparator"};
    done;

    appThatHasCodeChanges=${folderInFileToCommit[1]}

   if [[ "\t${apps[@]}\t"=~"\t${appThatHasCodeChanges}\t"  ]]; then
        testCommand=${appsCommands[$appThatHasCodeChanges]}
        commandsToExecute+=( $testCommand )
    fi
done

echo vingarium laviosa 
for index in "${!commandsToExecute[@]}"; do 
npm run ${commandsToExecute[$index]}; 
done
